### ISSUE TITLE
Show percent of votes in favor

### ISSUE THREAD

**Issue by thmosqueiro** [bjacobel/cabinet#18]
At face value, percent of votes in favor or ratio between Nay's and Yea's would be very interesting. Right out of the bat, this gives a clear vision of the situation. This seems simple to be implemented. For instance, once the votes are fetched, one could count number of Yea's and store in an object. Another idea, which I think is more promising, is calculating it as the page is constructed. This way, filters will be naturally applied (for instance, only democrats). In principle, this could be implemented in file [TabbleWrapper.js](https://github.com/bjacobel/cabinet/blob/master/src/components/TableWrapper.js). 

I did contact @bjacobel via Twitter about that, but unfortunately I couldn't stop and work on it more, so I wanted to leave this idea here in case someone with experience in React can implement it. I have the feeling this can be done in about 5min.

BTW great job!!

**Comment by bjacobel** [comment]
Hey @thmosqueiro! 

Thanks for adding your thoughts, I agree this would be a super valuable addition (and also agree with your thoughts on implementation). I'll let you know where I wind up with it.

Sorry the project's not in a great shape for others to hack on right now - threw it together pretty quickly and there's some nasty data transformation happening inside `render`, etc. Hopefully after I clean it up a bit it might be easier for others to jump back in.

**Comment by bjacobel** [comment]
FYI @thmosqueiro: https://github.com/bjacobel/cabinet/pull/19

**Comment by thmosqueiro** [comment]
Hey @bjacobel, thanks for taking the time for implementing it. I don't think it is in a bad shape, webdev is just not my forte. By far :)
